### ISSUE TITLE
[Bit.hdl] 值preOut从哪里获取的

### ISSUE THREAD

**Issue by LucasYao93** [woai3c/nand2tetris#11]
CHIP Bit {
    IN in, load;
    OUT out;

    PARTS:
    Mux(a = preOut, b = in, sel = load, out = o1);
    DFF(in = o1, out = preOut, out = out);
}

**Comment by woai3c** [comment]
DFF 触发器的特点是当前时钟的输出等于下一时钟的输出，所以 preOut 就是上一时钟的输出。

**Comment by LucasYao93** [comment]
> DFF 触发器的特点是当前时钟的输出等于下一时钟的输出。
> 所以 `a = preOut` 里的 preOut 就是上一时钟的输出，`out = preOut` 就是把当前时钟的输出赋值给 preOut。

了解了， 感谢
