### ISSUE TITLE
书下载不了？

### ISSUE THREAD

**Issue by PikaBin** [woai3c/nand2tetris#12]
点击书籍下载，跳转过去提示 invalid file

**Comment by woai3c** [comment]
> 点击书籍下载，跳转过去提示 invalid file

https://github.com/woai3c/recommended-books/blob/master/%E7%BC%96%E8%AF%91%E5%8E%9F%E7%90%86/%E8%AE%A1%E7%AE%97%E6%9C%BA%E7%B3%BB%E7%BB%9F%E8%A6%81%E7%B4%A0%EF%BC%9A%E4%BB%8E%E9%9B%B6%E5%BC%80%E5%A7%8B%E6%9E%84%E5%BB%BA%E7%8E%B0%E4%BB%A3%E8%AE%A1%E7%AE%97%E6%9C%BA.pdf

**Comment by PikaBin** [comment]
![image](https://user-images.githubusercontent.com/39492945/104864709-c6200e00-5974-11eb-8832-6fa27b2167ed.png)

**Comment by woai3c** [comment]
点右上角的 Download。

![image](https://user-images.githubusercontent.com/22117876/104864876-53636280-5975-11eb-8f35-445e9075b81a.png)

**Comment by PikaBin** [comment]
![Uploading image.png…]()

**Comment by PikaBin** [comment]
![image](https://user-images.githubusercontent.com/39492945/104865031-c79e0600-5975-11eb-9392-f8d72a892568.png)

**Comment by woai3c** [comment]
https://raw.githubusercontent.com/woai3c/recommended-books/master/%E7%BC%96%E8%AF%91%E5%8E%9F%E7%90%86/%E8%AE%A1%E7%AE%97%E6%9C%BA%E7%B3%BB%E7%BB%9F%E8%A6%81%E7%B4%A0%EF%BC%9A%E4%BB%8E%E9%9B%B6%E5%BC%80%E5%A7%8B%E6%9E%84%E5%BB%BA%E7%8E%B0%E4%BB%A3%E8%AE%A1%E7%AE%97%E6%9C%BA.pdf 试一下这个 我点了能下载

**Comment by PikaBin** [comment]
还是不行，点击过去还是提示如下图：

![image](https://user-images.githubusercontent.com/39492945/104865557-4cd5ea80-5977-11eb-8dfb-6591ca110626.png)

**Comment by PikaBin** [comment]
不然发我邮箱?
：1747320015@qq.com

**Comment by PikaBin** [comment]
我下载好了，原来你给的这个网址服务器是在美国的，我翻墙过去下载下来了
