### ISSUE TITLE
hello,我验算了一下你的代码，发现有误，我把我的贴上来了。

### ISSUE THREAD

**Issue by evancao7** [woai3c/nand2tetris#13]
https://github.com/woai3c/nand2tetris/blob/fffa7cffd727937a577781e0d1c797a13961568b/02/FullAdder.hdl#L13
HalfAdder(a=a, b=b, sum=sumab, carry=carryab);
HalfAdder(a=sumab, b=c, sum=sum, carry=carryabc);
Or(a=carryab, b=carryabc, out=carry);

**Comment by woai3c** [comment]
你的代码只是换了个变量名称。

**Comment by tohsaka888** [comment]
发现了同样的问题，这里用`Xor`运算，假设`a=0,b=0,c=0`的话，`c1`和`c2`都为0，`carry`输出不是1吗，但是编译好像可以通过，不知道是不是我理解错了，请大佬指点下（感觉应该用`Or`）

**Comment by woai3c** [comment]
> 发现了同样的问题，这里用`Xor`运算，假设`a=0,b=0,c=0`的话，`c1`和`c2`都为0，`carry`输出不是1吗，但是编译好像可以通过，不知道是不是我理解错了，请大佬指点下（感觉应该用`Or`）

a b c 全 0，其他结果肯定是全 0 啊，哪来的 1。

**Comment by tohsaka888** [comment]
> > 发现了同样的问题，这里用`Xor`运算，假设`a=0,b=0,c=0`的话，`c1`和`c2`都为0，`carry`输出不是1吗，但是编译好像可以通过，不知道是不是我理解错了，请大佬指点下（感觉应该用`Or`）
> 
> a b c 全 0，其他结果肯定是全 0 啊，哪来的 1。这用里 `Xor` 还是 `Or` 结果都是一样的，如果不理解可以把测试代码看一遍，代入运算一下。

知道哪错了，Xor真值表记劈叉了，谢谢大佬

**Comment by woai3c** [comment]
> > > 发现了同样的问题，这里用`Xor`运算，假设`a=0,b=0,c=0`的话，`c1`和`c2`都为0，`carry`输出不是1吗，但是编译好像可以通过，不知道是不是我理解错了，请大佬指点下（感觉应该用`Or`）
> > 
> > 
> > a b c 全 0，其他结果肯定是全 0 啊，哪来的 1。这用里 `Xor` 还是 `Or` 结果都是一样的，如果不理解可以把测试代码看一遍，代入运算一下。
> 
> 知道哪错了，Xor真值表记劈叉了，谢谢大佬

不客气  加油

**Comment by shangguantangyun** [comment]
你好，真是不好意思，验算我的哪些代码了呢？我好像并没有写过类似的代码？



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年03月19日 23:19 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | Re: [woai3c/nand2tetris] hello,我验算了一下你的代码，发现有误，我把我的贴上来了。 (#13) |

发现了同样的问题，这里用Xor运算，假设a=0,b=0,c=0的话，c1和c2都为0，carry输出不是1吗，但是编译好像可以通过，不知道是不是我理解错了，请大佬指点下（感觉应该用Or）

a b c 全 0，其他结果肯定是全 0 啊，哪来的 1。这用里 Xor 还是 Or 结果都是一样的，如果不理解可以把测试代码看一遍，代入运算一下。

知道哪错了，Xor真值表记劈叉了，谢谢大佬

不客气 加油
