### ISSUE TITLE
不好意思我之前的自己的补充部分写错了，我这边运行了一下你的代码，结果是错误的，具体可以看图。然后我把我通过的代码放上来，仅供参考。

### ISSUE THREAD

**Issue by evancao7** [woai3c/nand2tetris#14]
<img width="885" alt="Xnip2021-02-01_23-27-29" src="https://user-images.githubusercontent.com/39895686/106480369-49e60880-64e6-11eb-885b-9890d5dd5dbb.png">
这是我运行你的代码
1处是你的代码
2处是出错的具体地方
3处是系统提示运行到脚本第3行出现了错误

<img width="1024" alt="Xnip2021-02-01_23-34-13" src="https://user-images.githubusercontent.com/39895686/106480615-8b76b380-64e6-11eb-84bc-708031db00f5.png">
这是我的代码的运行结果
1处是我的代码内容
2处是运行结果
3处现实没有错误出现

```
 PARTS:

    Xor(a=a ,b=b ,out=temp);
    Xor(a=temp ,b=c ,out=sum);

    And(a=a ,b=b ,out=aAndb);
    And(a=b ,b=c ,out=bAndc);
    And(a=a ,b=c ,out=aAndc);
    Or(a=aAndb ,b=bAndc ,out=temp1);
    Or(a=temp1 ,b=aAndc ,out=carry);
```

**Comment by woai3c** [comment]
我的代码中引用了半加器，如果你没实现半加器，运行结果显示是错误的。

**Comment by evancao7** [comment]
这里你提到引用的半加器是指builtinchips文件夹中的HalfAdder.hdl吗？

**Comment by evancao7** [comment]
> 你运行我的代码出错，是因为我引用了半加器。如果你没实现半加器，运行结果显示是错误的。

这里你提到引用的半加器是指builtinchips文件夹中的HalfAdder.hdl吗？

**Comment by evancao7** [comment]
我在window跑了一下，你的代码是正确的。是我这边出现了问题，没有成功调用builtinchips中的hdl文件。
