### ISSUE TITLE
project  5下的CPU.hdl 中ALU计算的 x参数 与 y参数不能调换？

### ISSUE THREAD

**Issue by PikaBin** [woai3c/nand2tetris#15]
![question](https://user-images.githubusercontent.com/39492945/107146747-0592b680-6985-11eb-8b58-351a67a1f29e.png)
如附件图片框出，上面的x,y参数值如果调换过来（即按照下面这样写），就不会通过测试，这是为什么？求解答！

                   x = outAM, y = outDR,

**Comment by woai3c** [comment]
> ![question](https://user-images.githubusercontent.com/39492945/107146747-0592b680-6985-11eb-8b58-351a67a1f29e.png)
> 如附件图片框出，上面的x,y参数值如果调换过来（即按照下面这样写），就不会通过测试，这是为什么？求解答！
> 
> ```
>                x = outAM, y = outDR,
> ```

这是两个不同寄存器的输出，调换过来报错很正常。
