### ISSUE TITLE
07 生成的文件没有文件名

### ISSUE THREAD

**Issue by mlkr** [woai3c/nand2tetris#16]
如果路径是目录的话

  // 处理目录
  node vm-translator.js xxx

这样操作的话， 生成的文件为 .asm  没有文件名

**Comment by woai3c** [comment]
在对应目录下打开终端，执行 `node vm-translator.js StaticTest`，将会生成 `StaticTest.asm` 文件。
![image](https://user-images.githubusercontent.com/22117876/123201043-84c3f980-d4e4-11eb-9f4c-14ff084058d4.png)

**Comment by mlkr** [comment]
加个斜杠就会复现 例 node vm-translator.js StaticTest\

**Comment by mlkr** [comment]
![捕获](https://user-images.githubusercontent.com/9197250/123402122-fdf14880-d5d9-11eb-8996-76dce401e800.PNG)
而且只能处理一层目录， 多层就会失效

**Comment by woai3c** [comment]
这个代码就是针对测试文件写的，所以没有作过多处理。

**Comment by woai3c** [comment]
长时间没有响应，关闭。
