### ISSUE TITLE
07/MemoryAccess/StaticTest 不能通过测试用例

### ISSUE THREAD

**Issue by mlkr** [woai3c/nand2tetris#17]
![屏幕截图 2021-06-23 055821](https://user-images.githubusercontent.com/9197250/123043730-5209fa80-d42b-11eb-9001-7874ff275277.png)
 
可能是生成的汇编代码中@ 这里带了斜杠和冒号

![屏幕截图 2021-06-23 055933](https://user-images.githubusercontent.com/9197250/123044135-da889b00-d42b-11eb-9200-908a96ef8c4a.png)

**Comment by woai3c** [comment]
生成的代码有这个是不正常的
![image](https://user-images.githubusercontent.com/22117876/123201741-e042b700-d4e5-11eb-965b-3fd5cab60ab3.png)

**Comment by mlkr** [comment]
![image](https://user-images.githubusercontent.com/9197250/123395484-d5198500-d5d2-11eb-9e5c-a8e834fb27cc.png)
你这里没有处理文件名， 而且用 . 拼接 好像不太对  code-writer.js

**Comment by woai3c** [comment]
重复问题，请看 https://github.com/woai3c/nand2tetris/issues/16#issuecomment-868361784。
