### ISSUE TITLE
02/ALU.hdl 的一个小建议

### ISSUE THREAD

**Issue by modomodoplz** [woai3c/nand2tetris#22]
首先想和您说一声感谢，对于我这种刚入门的菜鸟提供了莫大的帮助。
在做project的时候，看到本书作者在project建议里面写到:
The remaining guidelines for this project are identical to those of project 1. In particular, remember that good HDL programs use as few chip-parts as possible, and there is no need to invent and implement any “helper chips”;  your HDL programs should use only chips that were specified in chapters 1 and 2.
当时就想怎么可以用他给的芯片文件写出ALU，但是遇到了点困难，于是来到您的github来寻找思路。但是发现在您的ALU.hdl里面使用了”helper chips“，即Or16Way还有IsNeg。后面我还是想按照作者的建议来写，于是有以下的解法，希望能给和我有相同疑惑的大家一点思路。
<img width="1153" alt="image" src="https://github.com/woai3c/nand2tetris/assets/116552049/48eeff83-44bf-45a1-8342-c860eca8e53a">

**Comment by woai3c** [comment]
好的，感谢你的建议。
