### ISSUE TITLE
博主QQ交流群无效

### ISSUE THREAD

**Issue by hardmanhong** [woai3c/nand2tetris#4]
偶然在知乎日常灌水，无意间看到博主分享的前端学习经历，对我甚是启发，特来github观摩，我本人也是一名前端开发者，大三开始自学前端，虽说已有近两年经验，工作以来也一直没有老大带领，靠自己学习新技术，自知水平尚未达到中级前端开发水平，遂想与博主请教，虽知做技术应该脚踏实地，但有时却很迷茫，最近刚入职，心中实在疑惑重重，顿感前途迷惘，若博主有时间，恳请指点一个菜鸟前端，感激不尽 :)

**Comment by woai3c** [comment]
QQ交流群挺正常的 有问题我基本都会回复 欢迎多提问题
如果你把这本书的项目都做完 提升到中级水平肯定是没问题的
